<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Include="wwwroot\images\frühlingsfest.jpg" />
    <None Include="wwwroot\js\script.js" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.13.1" />
    <PackageReference Include="MailKit" Version="4.8.0" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.EntityFrameworkCore" Version="8.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NLog.Extensions.Logging" Version="5.3.14" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="5.3.14" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.5" />
    <PackageReference Include="Syncfusion.Blazor.DropDowns" Version="27.1.57" />
    <PackageReference Include="Syncfusion.Blazor.Grid" Version="27.1.57" />
    <PackageReference Include="Syncfusion.Blazor.Navigations" Version="27.1.57" />
    <PackageReference Include="Syncfusion.Blazor.ProgressBar" Version="27.1.57" />
    <PackageReference Include="Syncfusion.Blazor.Schedule" Version="27.1.57" />
    <PackageReference Include="Syncfusion.Blazor.SplitButtons" Version="27.1.57" />
    <PackageReference Include="Syncfusion.Blazor.Themes" Version="27.1.57" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Components\Account\Pages\Member\Galerie\" />
    <Folder Include="Components\Account\Pages\Member\Verified\" />
    <Folder Include="Components\Shared\Inputs\" />
    <Folder Include="Models\Auth\" />
    <Folder Include="wwwroot\flowbite\dist\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\SfResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SfResources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\SfResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>SfResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Components\Pages\Impressum.razor" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="Components\Pages\Impressum.razor" />
  </ItemGroup>

</Project>
