// <auto-generated />
using System;
using BudoShurenWebsite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BudoShurenWebsite.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261003201930_BearbeitungsEntwuerfe")]
    partial class BearbeitungsEntwuerfe
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BudoShurenWebsite.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Abteilung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("Verified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VerifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.Abteilung", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Abteilungsleiter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kontaktperson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.ToTable("Abteilungen", (string)null);
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.AktuellesBeitrag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AbteilungId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Erstellt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErstelltVon")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("Geaendert")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeaendertVon")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MetaBeschreibung")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("MetaTitel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Veroeffentlicht")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AbteilungId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("AktuellesBeitraege", (string)null);
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.AktuellesBild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BildId")
                        .HasColumnType("int");

                    b.Property<int>("BlockId")
                        .HasColumnType("int");

                    b.Property<int>("Sortierung")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BildId");

                    b.HasIndex("BlockId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("AktuellesBilder", (string)null);
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.AktuellesBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BeitragId")
                        .HasColumnType("int");

                    b.Property<string>("BildUnterschrift")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("BilderProReihe")
                        .HasColumnType("int");

                    b.Property<string>("MarkdownInhalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sortierung")
                        .HasColumnType("int");

                    b.Property<int>("Typ")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BeitragId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("AktuellesBloecke", (string)null);
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.AppointmentData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abteilung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AlternativeColor")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntryCreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastChange")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastChangedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecurrenceException")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecurrenceID")
                        .HasColumnType("int");

                    b.Property<string>("RecurrenceRule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ShowInMonth")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowInWeek")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VeranstaltungsTagId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("VeranstaltungsTagId")
                        .IsUnique()
                        .HasFilter("[VeranstaltungsTagId] IS NOT NULL");

                    b.ToTable("Appointments", (string)null);
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.BearbeitungsEntwurf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BenutzerId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Daten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GeaendertUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Schluessel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BenutzerId", "Schluessel")
                        .IsUnique();

                    b.ToTable("BearbeitungsEntwuerfe", (string)null);
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.BildVariante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Art")
                        .HasColumnType("int");

                    b.Property<int>("BildId")
                        .HasColumnType("int");

                    b.Property<int>("Breite")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Daten")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("ErstelltUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Hoehe")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BildId", "Art")
                        .IsUnique();

                    b.ToTable("BildVarianten", (string)null);
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.DbImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Breite")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Hoehe")
                        .HasColumnType("int");

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VorlaeufigSeitUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("VorlaeufigSeitUtc")
                        .HasFilter("[VorlaeufigSeitUtc] IS NOT NULL");

                    b.ToTable("Images", (string)null);
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.EmailAusgang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("An")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("AnhaengeJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AntwortAn")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("Betreff")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("BezugId")
                        .HasColumnType("int");

                    b.Property<string>("BezugTyp")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ErstelltUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FaelligAbUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GesendetAmUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Html")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LetzterFehler")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Prioritaet")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Versuche")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Status", "Prioritaet", "FaelligAbUtc");

                    b.ToTable("EmailAusgang", (string)null);
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.EmailSetting", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<string>("SmtpPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("int");

                    b.Property<string>("SmtpServer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmtpUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.ToTable("EmailSettings", (string)null);
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.GalerieEintrag", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Aikido")
                        .HasColumnType("bit");

                    b.Property<string>("Beschreibung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Bujinkan")
                        .HasColumnType("bit");

                    b.Property<int?>("DbImageId")
                        .HasColumnType("int");

                    b.Property<string>("EntryCreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EntryCreationDateUTC")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Genbukan")
                        .HasColumnType("bit");

                    b.Property<bool>("Home")
                        .HasColumnType("bit");

                    b.Property<bool>("Iaido")
                        .HasColumnType("bit");

                    b.Property<string>("ImageCreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ImageDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Jodo")
                        .HasColumnType("bit");

                    b.Property<string>("LastChangedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastChangedUTC")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Untertitel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Öffentlich")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("DbImageId")
                        .IsUnique()
                        .HasFilter("[DbImageId] IS NOT NULL");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.ToTable("Galerie", (string)null);
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.Neuigkeit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("Ablaufdatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DbImageId")
                        .HasColumnType("int");

                    b.Property<string>("EntryCreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IstStandardneuigkeit")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastChange")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastChangedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Linktext")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ort")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Quellenangabe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sortierung")
                        .HasColumnType("int");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DbImageId")
                        .IsUnique()
                        .HasFilter("[DbImageId] IS NOT NULL");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.ToTable("Neuigkeiten", (string)null);
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.Veranstaltungen.Anmeldung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AdminGesehenUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("AdminNotiz")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("AnzahlBegleitpersonen")
                        .HasColumnType("int");

                    b.Property<string>("Bemerkung")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("DatenschutzAkzeptiertUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTime?>("EmailBestaetigtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ErstelltUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GeaendertUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Graduierung")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NeueEmail")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<byte[]>("NeueEmailTokenHash")
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.Property<int>("Quelle")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReserviertBisUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StatusGrund")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("TokenErstelltUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.Property<int>("VeranstaltungId")
                        .HasColumnType("int");

                    b.Property<string>("Verein")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("NeueEmailTokenHash")
                        .IsUnique()
                        .HasFilter("[NeueEmailTokenHash] IS NOT NULL");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("VeranstaltungId", "Email")
                        .IsUnique();

                    b.ToTable("Anmeldungen", (string)null);
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.Veranstaltungen.AnmeldungEreignis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Akteur")
                        .HasColumnType("int");

                    b.Property<string>("AkteurUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AnmeldungId")
                        .HasColumnType("int");

                    b.Property<int>("Art")
                        .HasColumnType("int");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ZeitpunktUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AnmeldungId", "ZeitpunktUtc");

                    b.ToTable("AnmeldungEreignisse", (string)null);
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.Veranstaltungen.AnmeldungInfoEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AbgemeldetUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("AbmeldeTokenHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.Property<int>("AnmeldungId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.HasKey("Id");

                    b.HasIndex("AbmeldeTokenHash")
                        .IsUnique();

                    b.HasIndex("AnmeldungId", "Email")
                        .IsUnique();

                    b.ToTable("AnmeldungInfoEmails", (string)null);
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.Veranstaltungen.AnmeldungTag", b =>
                {
                    b.Property<int>("AnmeldungId")
                        .HasColumnType("int");

                    b.Property<int>("VeranstaltungsTagId")
                        .HasColumnType("int");

                    b.HasKey("AnmeldungId", "VeranstaltungsTagId");

                    b.HasIndex("VeranstaltungsTagId");

                    b.ToTable("AnmeldungTage", (string)null);
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.Veranstaltungen.BenachrichtigungEmpfaenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AbgemeldetUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("AbmeldeTokenHash")
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.Property<DateTime>("BenachrichtigtBisUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<int>("Ereignisse")
                        .HasColumnType("int");

                    b.Property<DateTime>("ErstelltUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("HinzugefuegtVon")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Modus")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("VeranstaltungId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AbmeldeTokenHash")
                        .IsUnique()
                        .HasFilter("[AbmeldeTokenHash] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.HasIndex("VeranstaltungId", "Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("VeranstaltungId", "UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("BenachrichtigungEmpfaenger", null, t =>
                        {
                            t.HasCheckConstraint("CK_BenachrichtigungEmpfaenger_UserIdOderEmail", "(CASE WHEN [UserId] IS NULL THEN 0 ELSE 1 END) + (CASE WHEN [Email] IS NULL THEN 0 ELSE 1 END) = 1");
                        });
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.Veranstaltungen.Veranstaltung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AbteilungId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Adresse")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("AenderungenBis")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AnmeldungAb")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AnmeldungBis")
                        .HasColumnType("datetime2");

                    b.Property<int>("BemerkungFeld")
                        .HasColumnType("int");

                    b.Property<bool>("DoubleOptIn")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ErstelltUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErstelltVon")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ErstmalsVeroeffentlichtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GeaendertUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeaendertVon")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("GraduierungFeld")
                        .HasColumnType("int");

                    b.Property<string>("KartenLink")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("KontaktEmail")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("KontaktName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Kurzbeschreibung")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaxBegleitpersonen")
                        .HasColumnType("int");

                    b.Property<int?>("MaxTeilnehmerVorgabe")
                        .HasColumnType("int");

                    b.Property<int>("MinTageBeiTeilanmeldung")
                        .HasColumnType("int");

                    b.Property<string>("Ort")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("PrivateVeranstaltung")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Sichtbarkeit")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Teilnahmemodus")
                        .HasColumnType("int");

                    b.Property<int>("TelefonFeld")
                        .HasColumnType("int");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("VereinFeld")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("ZusammenfassungUhrzeit")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("AbteilungId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Veranstaltungen", (string)null);
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.Veranstaltungen.VeranstaltungBild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BildId")
                        .HasColumnType("int");

                    b.Property<int>("BlockId")
                        .HasColumnType("int");

                    b.Property<int>("Sortierung")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BildId");

                    b.HasIndex("BlockId");

                    b.ToTable("VeranstaltungBilder", (string)null);
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.Veranstaltungen.VeranstaltungBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BildUnterschrift")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("BilderProReihe")
                        .HasColumnType("int");

                    b.Property<string>("MarkdownInhalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sortierung")
                        .HasColumnType("int");

                    b.Property<int>("Typ")
                        .HasColumnType("int");

                    b.Property<int>("VeranstaltungId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VeranstaltungId");

                    b.ToTable("VeranstaltungBloecke", (string)null);
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.Veranstaltungen.VeranstaltungNachricht", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AnInfoAdressen")
                        .HasColumnType("bit");

                    b.Property<int>("AnzahlEmpfaenger")
                        .HasColumnType("int");

                    b.Property<int>("Art")
                        .HasColumnType("int");

                    b.Property<string>("Betreff")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ErstelltVon")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("GesendetUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("InhaltMarkdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VeranstaltungId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VeranstaltungId", "GesendetUtc");

                    b.ToTable("VeranstaltungNachrichten", (string)null);
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.Veranstaltungen.VeranstaltungsTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Abgesagt")
                        .HasColumnType("bit");

                    b.Property<TimeOnly>("Beginn")
                        .HasColumnType("time");

                    b.Property<DateOnly>("Datum")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("Ende")
                        .HasColumnType("time");

                    b.Property<int?>("MaxTeilnehmer")
                        .HasColumnType("int");

                    b.Property<string>("Titel")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("VeranstaltungId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VeranstaltungId", "Datum", "Beginn");

                    b.ToTable("VeranstaltungsTage", (string)null);
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.Visit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("PageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("VisitorID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.ToTable("Visit", (string)null);
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.WissenBeitrag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AbteilungLink")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Erstellt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErstelltVon")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("Geaendert")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeaendertVon")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HeadlineAnekdote")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HeadlineTitel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("KategorieId")
                        .HasColumnType("int");

                    b.Property<string>("MetaBeschreibung")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("MetaTitel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Veroeffentlicht")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("KategorieId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("WissenBeitraege", (string)null);
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.WissenBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("BannerAusblenden")
                        .HasColumnType("bit");

                    b.Property<string>("BannerTitel")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("BeitragId")
                        .HasColumnType("int");

                    b.Property<int?>("BildId")
                        .HasColumnType("int");

                    b.Property<string>("BildPosition")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ListenItemsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sortierung")
                        .HasColumnType("int");

                    b.Property<string>("TextInhalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextInhalt2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Typ")
                        .HasColumnType("int");

                    b.Property<string>("UntertitelText")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("BeitragId");

                    b.HasIndex("BildId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("WissenBloecke", (string)null);
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.WissenKategorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AbteilungId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AbteilungId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("WissenKategorien", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Allgemein",
                            Slug = "allgemein",
                            SortOrder = 0
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.AktuellesBeitrag", b =>
                {
                    b.HasOne("BudoShurenWebsite.Models.Abteilung", "Abteilung")
                        .WithMany()
                        .HasForeignKey("AbteilungId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Abteilung");
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.AktuellesBild", b =>
                {
                    b.HasOne("BudoShurenWebsite.Models.DbImage", "Bild")
                        .WithMany()
                        .HasForeignKey("BildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudoShurenWebsite.Models.AktuellesBlock", "Block")
                        .WithMany("Bilder")
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bild");

                    b.Navigation("Block");
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.AktuellesBlock", b =>
                {
                    b.HasOne("BudoShurenWebsite.Models.AktuellesBeitrag", "Beitrag")
                        .WithMany("Bloecke")
                        .HasForeignKey("BeitragId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beitrag");
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.AppointmentData", b =>
                {
                    b.HasOne("BudoShurenWebsite.Models.Veranstaltungen.VeranstaltungsTag", null)
                        .WithMany()
                        .HasForeignKey("VeranstaltungsTagId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.BearbeitungsEntwurf", b =>
                {
                    b.HasOne("BudoShurenWebsite.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("BenutzerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.BildVariante", b =>
                {
                    b.HasOne("BudoShurenWebsite.Models.DbImage", null)
                        .WithMany()
                        .HasForeignKey("BildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.GalerieEintrag", b =>
                {
                    b.HasOne("BudoShurenWebsite.Models.DbImage", "DbImage")
                        .WithOne("GalerieEintrag")
                        .HasForeignKey("BudoShurenWebsite.Models.GalerieEintrag", "DbImageId");

                    b.Navigation("DbImage");
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.Neuigkeit", b =>
                {
                    b.HasOne("BudoShurenWebsite.Models.DbImage", "DbImage")
                        .WithOne("Neuigkeit")
                        .HasForeignKey("BudoShurenWebsite.Models.Neuigkeit", "DbImageId");

                    b.Navigation("DbImage");
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.Veranstaltungen.Anmeldung", b =>
                {
                    b.HasOne("BudoShurenWebsite.Models.Veranstaltungen.Veranstaltung", "Veranstaltung")
                        .WithMany("Anmeldungen")
                        .HasForeignKey("VeranstaltungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veranstaltung");
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.Veranstaltungen.AnmeldungEreignis", b =>
                {
                    b.HasOne("BudoShurenWebsite.Models.Veranstaltungen.Anmeldung", "Anmeldung")
                        .WithMany("Ereignisse")
                        .HasForeignKey("AnmeldungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anmeldung");
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.Veranstaltungen.AnmeldungInfoEmail", b =>
                {
                    b.HasOne("BudoShurenWebsite.Models.Veranstaltungen.Anmeldung", "Anmeldung")
                        .WithMany("InfoEmails")
                        .HasForeignKey("AnmeldungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anmeldung");
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.Veranstaltungen.AnmeldungTag", b =>
                {
                    b.HasOne("BudoShurenWebsite.Models.Veranstaltungen.Anmeldung", "Anmeldung")
                        .WithMany("Tage")
                        .HasForeignKey("AnmeldungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudoShurenWebsite.Models.Veranstaltungen.VeranstaltungsTag", "VeranstaltungsTag")
                        .WithMany("AnmeldungTage")
                        .HasForeignKey("VeranstaltungsTagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Anmeldung");

                    b.Navigation("VeranstaltungsTag");
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.Veranstaltungen.BenachrichtigungEmpfaenger", b =>
                {
                    b.HasOne("BudoShurenWebsite.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BudoShurenWebsite.Models.Veranstaltungen.Veranstaltung", "Veranstaltung")
                        .WithMany("BenachrichtigungEmpfaenger")
                        .HasForeignKey("VeranstaltungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Veranstaltung");
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.Veranstaltungen.Veranstaltung", b =>
                {
                    b.HasOne("BudoShurenWebsite.Models.Abteilung", "Abteilung")
                        .WithMany()
                        .HasForeignKey("AbteilungId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Abteilung");
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.Veranstaltungen.VeranstaltungBild", b =>
                {
                    b.HasOne("BudoShurenWebsite.Models.DbImage", "Bild")
                        .WithMany()
                        .HasForeignKey("BildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BudoShurenWebsite.Models.Veranstaltungen.VeranstaltungBlock", "Block")
                        .WithMany("Bilder")
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bild");

                    b.Navigation("Block");
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.Veranstaltungen.VeranstaltungBlock", b =>
                {
                    b.HasOne("BudoShurenWebsite.Models.Veranstaltungen.Veranstaltung", "Veranstaltung")
                        .WithMany("Bloecke")
                        .HasForeignKey("VeranstaltungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veranstaltung");
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.Veranstaltungen.VeranstaltungNachricht", b =>
                {
                    b.HasOne("BudoShurenWebsite.Models.Veranstaltungen.Veranstaltung", "Veranstaltung")
                        .WithMany()
                        .HasForeignKey("VeranstaltungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veranstaltung");
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.Veranstaltungen.VeranstaltungsTag", b =>
                {
                    b.HasOne("BudoShurenWebsite.Models.Veranstaltungen.Veranstaltung", "Veranstaltung")
                        .WithMany("Tage")
                        .HasForeignKey("VeranstaltungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veranstaltung");
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.WissenBeitrag", b =>
                {
                    b.HasOne("BudoShurenWebsite.Models.WissenKategorie", "Kategorie")
                        .WithMany("Beitraege")
                        .HasForeignKey("KategorieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kategorie");
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.WissenBlock", b =>
                {
                    b.HasOne("BudoShurenWebsite.Models.WissenBeitrag", "Beitrag")
                        .WithMany("Bloecke")
                        .HasForeignKey("BeitragId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudoShurenWebsite.Models.DbImage", "Bild")
                        .WithMany()
                        .HasForeignKey("BildId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Beitrag");

                    b.Navigation("Bild");
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.WissenKategorie", b =>
                {
                    b.HasOne("BudoShurenWebsite.Models.Abteilung", "Abteilung")
                        .WithMany()
                        .HasForeignKey("AbteilungId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Abteilung");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BudoShurenWebsite.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BudoShurenWebsite.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudoShurenWebsite.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BudoShurenWebsite.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.AktuellesBeitrag", b =>
                {
                    b.Navigation("Bloecke");
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.AktuellesBlock", b =>
                {
                    b.Navigation("Bilder");
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.DbImage", b =>
                {
                    b.Navigation("GalerieEintrag");

                    b.Navigation("Neuigkeit");
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.Veranstaltungen.Anmeldung", b =>
                {
                    b.Navigation("Ereignisse");

                    b.Navigation("InfoEmails");

                    b.Navigation("Tage");
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.Veranstaltungen.Veranstaltung", b =>
                {
                    b.Navigation("Anmeldungen");

                    b.Navigation("BenachrichtigungEmpfaenger");

                    b.Navigation("Bloecke");

                    b.Navigation("Tage");
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.Veranstaltungen.VeranstaltungBlock", b =>
                {
                    b.Navigation("Bilder");
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.Veranstaltungen.VeranstaltungsTag", b =>
                {
                    b.Navigation("AnmeldungTage");
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.WissenBeitrag", b =>
                {
                    b.Navigation("Bloecke");
                });

            modelBuilder.Entity("BudoShurenWebsite.Models.WissenKategorie", b =>
                {
                    b.Navigation("Beitraege");
                });
#pragma warning restore 612, 618
        }
    }
}
